image: python:latest

before_script:
  - git config --global user.name "Vitaliy Filyuchkov"
  - git config --global user.email "philyuchkoff@gmail.com"
  - pip install mkdocs mkdocs-material pymdown-extensions mkdocs-awesome-pages-plugin mkdocs-minify-plugin pygments-bsl mkdocs-git-revision-date-localized-plugin mkdocs-mermaid2-plugin

variables:
  GIT_DEPTH: 20

pages:
  stage: build
  image: python:latest
  script:
    - mkdocs build -d public
    - echo "Pages accessible through ${CI_PAGES_URL}/${PAGES_PREFIX}"
#  - mv site public
  variables:
    PAGES_PREFIX: "" # No prefix by default (master)
  pages:
    path_prefix: "$PAGES_PREFIX"
  artifacts:
    paths:
      - public
